apiVersion: 1
datasources:
  - name: InfluxDB-MintFV
    type: influxdb
    access: proxy
    url: http://influxdb:8181
    jsonData:
      dbName: mintfv
      insecureGrpc: true
      pdcInjected: false
      version: SQL
    isDefault: true
    editable: true
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
