{
 "title": "uwboxXY Dashboard (Temperatur, Taupunkt, Feuchtigkeit)",
 "tags": [
  "mintfv",
  "uwbox",
  "share"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Temp Min",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT concat(value::STRING, ' °C - ', right(tenant_id, 7)) AS result\nFROM sensors\nWHERE tenant_id LIKE 'de-hh-mintfv-uwbox%'\n  AND sensor_type = 'temperature'\n  AND value < 900\n  AND $__timeFilter(time)\nORDER BY value ASC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Temp Max",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT concat(value::STRING, ' °C - ', right(tenant_id, 7)) AS result\nFROM sensors\nWHERE tenant_id LIKE 'de-hh-mintfv-uwbox%'\n  AND sensor_type = 'temperature'\n  AND value < 900\n  AND $__timeFilter(time)\nORDER BY value DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Dewpoint Min",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT concat(value::STRING, ' °C - ', right(tenant_id, 7)) AS result\nFROM sensors\nWHERE tenant_id LIKE 'de-hh-mintfv-uwbox%'\n  AND sensor_type = 'dewpoint'\n  AND value < 900\n  AND $__timeFilter(time)\nORDER BY value ASC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Dewpoint Max",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT concat(value::STRING, ' °C - ', right(tenant_id, 7)) AS result\nFROM sensors\nWHERE tenant_id LIKE 'de-hh-mintfv-uwbox%'\n  AND sensor_type = 'dewpoint'\n  AND value < 900\n  AND $__timeFilter(time)\nORDER BY value DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Humidity Min",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT concat(value::STRING, ' % - ', right(tenant_id, 7)) AS result\nFROM sensors\nWHERE tenant_id LIKE 'de-hh-mintfv-uwbox%'\n  AND sensor_type = 'humidity'\n  AND value < 900\n  AND $__timeFilter(time)\nORDER BY value ASC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Humidity Max",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT concat(value::STRING, ' % - ', right(tenant_id, 7)) AS result\nFROM sensors\nWHERE tenant_id LIKE 'de-hh-mintfv-uwbox%'\n  AND sensor_type = 'humidity'\n  AND value < 900\n  AND $__timeFilter(time)\nORDER BY value DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  value AS \" \",\n  tenant_id AS metric\nFROM sensors\nWHERE tenant_id LIKE 'de-hh-mintfv-uwbox%'\n  AND sensor_type = 'temperature'\n  AND value < 900\n  AND $__timeFilter(time)\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Dewpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  value AS \" \",\n  tenant_id AS metric\nFROM sensors\nWHERE tenant_id LIKE 'de-hh-mintfv-uwbox%'\n  AND sensor_type = 'dewpoint'\n  AND value < 900\n  AND $__timeFilter(time)\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  value AS \" \",\n  tenant_id AS metric\nFROM sensors\nWHERE tenant_id LIKE 'de-hh-mintfv-uwbox%'\n  AND sensor_type = 'humidity'\n  AND value < 900\n  AND $__timeFilter(time)\nORDER BY time ASC;"
    }
   ]
  }
 ]
}