worker_processes auto;

# error_log /dev/stderr notice;
error_log /dev/stderr error;  # Nur echte Errors
pid        /run/nginx.pid;

events {
    worker_connections 1024;
}

# STREAM-Bereich für MQTT separat
include /etc/nginx/stream.d/*.conf;

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                   '$status $body_bytes_sent "$http_referer" '
    #                   '"$http_user_agent" "$http_x_forwarded_for"';


    # In your http { ... } block in nginx.conf
    log_format security '$remote_addr - [$time_local] '
                  '"$request" $status $body_bytes_sent '
                  '"$http_referer" "$http_user_agent" '
                  'reason=$log_reason';

    # WICHTIG: Globales Logging deaktivieren,
    # damit NUR die access_log-Einträge in ssl.conf greifen.
    access_log off;

    sendfile on;
    keepalive_timeout 120s;

    # gzip optional
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types text/plain text/css text/xml text/javascript
            application/x-javascript application/xml+rss
            application/json application/javascript;
    gzip_disable "msie6";

    # muss noch austariert werden
    client_max_body_size 10M;
    client_body_buffer_size 128k;
    client_body_timeout 120s;
    client_header_timeout 30s;
    send_timeout 120s;


    ### REQUEST SIZE & BUFFER LIMITS
    # Normal-Case Header Buffer (1 KB reicht meist)
    client_header_buffer_size 1k;

    # Falls Header/URI größer: max. 4 Buffer à 8 KB = 32 KB gesamt
    # Die URI-Länge ist auf 8 KB begrenzt!
    # large_client_header_buffers 4 8k;
    large_client_header_buffers 2 4k;

    # 1. Rate Limits und Maps ZUERST (nur 00-*.conf)
    include /etc/nginx/conf.d/00-*.conf;

    # 2. Server Blocks (01-* bis 09-* und 10-* aufwärts, OHNE 00-*)
    include /etc/nginx/conf.d/0[1-9]-*.conf;
    include /etc/nginx/conf.d/[1-9][0-9]-*.conf;
}
