worker_processes auto;

# error_log  /var/log/nginx/error.log notice;
error_log /dev/stderr notice;
pid        /run/nginx.pid;

events {
    worker_connections 1024;
}

# STREAM-Bereich für MQTT separat
include /etc/nginx/stream.d/*.conf;

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                   '$status $body_bytes_sent "$http_referer" '
    #                   '"$http_user_agent" "$http_x_forwarded_for"';


    # WICHTIG: Globales Logging deaktivieren,
    # damit NUR die access_log-Einträge in ssl.conf greifen.
    access_log off;

    sendfile on;
    keepalive_timeout 65;

    # gzip optional
    gzip on;

    # 1. Rate Limits und Maps ZUERST (nur 00-*.conf)
    include /etc/nginx/conf.d/00-*.conf;

    # 2. Server Blocks (01-* bis 09-* und 10-* aufwärts, OHNE 00-*)
    include /etc/nginx/conf.d/0[1-9]-*.conf;
    include /etc/nginx/conf.d/[1-9][0-9]-*.conf;
}
